insert into CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)  values (1001,'USD','INR',65,'');
insert into CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)  values (1002,'USD','HKD',165,'');
insert into CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)  values (1003,'INR','USD',1,'');
insert into CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)  values (1004,'CNY','INR',142,'');
insert into CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)  values (1005,'USD','CNY',25,'');